name: Test

on:
  push:
    branches: [develop, main, "release*", "hotfix*"]
  pull_request:
    branches: [develop, main, "release*", "**"]

jobs:
  rspec:
    uses: ./.github/workflows/setup.yml#setup
    name: Run RSpec tests
    runs-on: ubuntu-latest

    steps:
    - name: Run RSpec
      run: bundle exec test && bundle exec rails -v

  cucumber:
    uses: ./.github/workflows/setup.yml#setup
    name: Run Cucumber tests
    runs-on: ubuntu-latest

    steps:
    - name: Run Cucumber
      run: bundle exec test && bundle exec rake --version
